name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: woo kubernetes test enviroment
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test
        env:
          DEFAULT_EMAIL: ${{ vars.DEFAULT_EMAIL }}
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
          DEFAULT_OTP_SECRET: ${{ secrets.DEFAULT_OTP_SECRET }}
          ADMIN_EMAIL: ${{ vars.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_OTP_SECRET: ${{ secrets.ADMIN_OTP_SECRET }}
          GPP_APP_BASE_URL: ${{ vars.GPP_APP_BASE_URL }}
          GPP_PUBLICATIEBANK_BASE_URL: ${{ vars.GPP_PUBLICATIEBANK_BASE_URL }}
      - uses: actions/upload-pages-artifact@v3
        if: ${{ !cancelled() }}
        with:
          path: playwright-report/
  deploy:
    if: ${{ !cancelled() }}
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
